version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - /home/ubuntu/database:/var/lib/postgresql/data
  backend:
    image: yusuf007r/task-manager:latest
    restart: always
    depends_on:
      - db
    ports:
      - '80:3000'
    env_file:
      - .env
