name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yusuf007r/task-manager:latest
      - name: executing remote ssh commands
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ubuntu
          key: ${{ secrets.SSH_KEY }}
          command: |
            cd task-manager-backend
            sudo docker-compose pull
            sudo docker-compose up -d
